# Generated by Django 4.1.1 on 2022-09-23 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=20)),
                ('m_pw', models.CharField(max_length=100)),
                ('m_gender', models.CharField(max_length=30)),
                ('m_hobby', models.CharField(max_length=100)),
                ('m_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 23, 16, 19, 21, 99341))),
            ],
        ),
    ]
