# Generated by Django 4.1.1 on 2022-09-23 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 23, 16, 19, 21, 99341)),
        ),
    ]
